<?php

namespace Tests\Feature\app\Http\Controllers\Api\Payments;

use App\Entities\Users\User;
use App\Models\CashRegister;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Tests\TestCase;

/**
 * Class PaymentControllerTest
 * @package Tests\Feature\app\Http\Controllers\Api\Payments
 * @author Daniel Romero - 123romerod@gmail.com
 */
class PaymentControllerTest extends TestCase
{
    use WithoutMiddleware, RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * This function aims to simulate a validation error when making a payment
     */
    public function testCreatePaymentErrorFields(): void
    {
        $data = [];

        $request = $this->post(route('payment.createPayment'), $data, ['Accept' => 'application/json']);

        $request->assertStatus(422)
            ->assertJson([
                'message' => [
                    'customer_payment' => [
                        'The customer payment field is required.'
                    ],
                    'amount_payable' => [
                        'The amount payable field is required.'
                    ],
                    'payment_denomination' => [
                        'The payment denomination field is required.'
                    ]
                ]
            ]);
    }

    /**
     * This function aims to simulate a successful payment
     */
    public function testCreatePaymentSuccess():void
    {
        factory(User::class)->create();

        factory(CashRegister::class, 100)->create();

        $data = [
            'customer_payment'      => '50000',
            'amount_payable'        => '10000',
            'payment_denomination'  => 'bill'
        ];

        $request = $this->post(route('payment.createPayment'), $data, ['Accept' => 'application/json']);

        $request->assertStatus(200);
    }

    /**
     * This function aims to simulate a server error when making a payment and there is no user in session
     */
    public function testCreatePaymentErrorNotUser():void
    {
        $data = [
            'customer_payment'      => '50000',
            'amount_payable'        => '20000',
            'payment_denomination'  => 'bill'
        ];

        $request = $this->post(route('payment.createPayment'), $data, ['Accept' => 'application/json']);

        $request->assertStatus(500);
    }

    /**
     * This function aims to simulate a server error when making a payment and there is no money to return
     */
    public function testCreatePaymentErrorNotReturnCash():void
    {
        factory(CashRegister::class, 1)->create();

        $data = [
            'customer_payment'      => '50000',
            'amount_payable'        => '10000',
            'payment_denomination'  => 'bill'
        ];

        $request = $this->post(route('payment.createPayment'), $data, ['Accept' => 'application/json']);

        $request->assertStatus(500);
    }
}
