<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Class CashRegister
 * @package App\Entities\CashRegisters
 * @author Daniel Romero - 123romerod@gmail.com
 */
class CashRegister extends Model
{
    /**
     * @var string
     */
    protected $table = 'cash_registers';

    /**
     * @var string[]
     */
    protected $fillable = [
        'id',
        'denomination',
        'value',
        'quantity',
        'created_at',
        'updated_at',
    ];

    /**
     * @var string[]
     */
    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    /**
     * @var string[]
     */
    protected $guarded = [
        'id',
        'created_at',
        'updated_at',
    ];

    /**
     * @var string[]
     */
    protected $dates = [
        'created_at',
        'updated_at',
    ];

    /**
     * @return BelongsToMany
     */
    public function transactionLogs(): BelongsToMany
    {
        return $this->belongsToMany(TransactionLog::class); // TODO: Change the autogenerated stub
    }
}
