<?php

namespace Tests\Feature\app\Http\Controllers\Api\CashRegisters;

use App\Entities\CashRegisters\CashRegister;
use App\Entities\CashRegisters\Repositories\Interfaces\CashRegisterRepositoryInterface;
use App\Entities\Users\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use InvalidArgumentException;
use Tests\TestCase;

/**
 * Class CashRegisterControllerTest
 * @package Tests\Feature\app\Http\Controllers\Api\CashRegisters
 * @author Daniel Romero - 123romerod@gmail.com
 */
class CashRegisterControllerTest extends TestCase
{
    use WithoutMiddleware, RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * This function aims to simulate the creation of the cash register's money base
     */
    public function testCreateMoneyBaseCashRegisterSuccess(): void
    {
        factory(User::class)->create();

        $data = [
            'denomination' => 'bill',
            'value' => '50000',
            'quantity' => '1'
        ];

        $request = $this->post(route('cashRegister.create'), $data, ['Accept' => 'application/json']);

        $request->assertStatus(200);

        $this->assertDatabaseHas('cash_registers', $data);
    }

    /**
     * This function aims to simulate a validation error when creating the monetary base of the cash register
     */
    public function testCreateMoneyBaseCashRegisterErrorFields(): void
    {
        $data = [];

        $request = $this->post(route('cashRegister.create'), $data, ['Accept' => 'application/json']);

        $request->assertStatus(422)
            ->assertJson([
                'message' => 'The given data was invalid.',
                'errors' => [
                    'denomination' => [
                        'The denomination field is required.'
                    ],
                    'value' => [
                        'The value field is required.'
                    ],
                    'quantity' => [
                        'The quantity field is required.'
                    ]
                ]
            ]);
    }

    /**
     * @throws InvalidArgumentException
     * This function aims to simulate a server error when creating the cash register of the cash register
     */
    public function testCreateMoneyBaseCashRegisterError(): void
    {
        $data = [
            'denomination' => 'bill',
            'value' => '50000',
            'quantity' => '1'
        ];

        $cashRegisterMock = \Mockery::mock(CashRegisterRepositoryInterface::class);

        $cashRegisterMock->shouldReceive('createOrUpdateCashRegister')
            ->withArgs($data)
            ->andThrow(new \Exception('data error'))
            ->getMock();

        $this->app->instance(CashRegisterRepositoryInterface::class, $cashRegisterMock);

        $request = $this->post(route('cashRegister.create'), $data, ['Accept' => 'application/json']);

        $request->assertStatus(500);
    }

    /**
     *  This function aims to simulate a successful query of the cash register status
     */
    public function testCheckStatusCashRegisterSuccess(): void
    {
        factory(CashRegister::class, 10)->create();

        $request = $this->get(route('cashRegister.getStatus'), ['Accept' => 'application/json']);

        $request->assertStatus(200)->assertJsonStructure([
            'status',
            'message' => [
                'total_cash_register',
                'coin',
                'total_coin',
                'bill',
                'total_bill'
            ]
        ]);

    }

    /**
     * This function aims to simulate the action of emptying the cash register successfully
     */
    public function testWithdrawAllMoneyCashRegisterSuccess(): void
    {
        factory(CashRegister::class, 10)->create();

        $request = $this->get(route('cashFlow.withdrawAllMoney'), ['Accept' => 'application/json']);

        $request->assertStatus(200);
    }


    public function testWithdrawAllMoneyCashRegisterError(): void
    {
        $request = $this->get(route('cashFlow.withdrawAllMoney'), ['Accept' => 'application/json']);

        $request->assertStatus(500);
    }
}
